server:
  port: 8888

spring:
  application:
    name: yesaladin-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/config
logging:
  config: classpath:logback-spring-native.xml

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus, gateway, health
      base-path: /monitor
      path-mapping:
        health: /l7check